JKR/documentation/api/urls.py
from django.urls import path
from .views import ListItems
app_name = 'documentation'
urlpatterns = [
    path('create/', ListItems.as_view(), name='create_documentation'),
]

JKR/home/urls.py
from django.urls import path
from .views import HomePage, DocumentationPage

urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    path('documentation/', DocumentationPage.as_view(), name='documentation_page'),
]

JKR/snippets/api/urls.py
from django.urls import path
from .views import ListItems
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

urlpatterns = [
    path('', ListItems.as_view(), name='supplier-list-create'),
    path('schema/', SpectacularAPIView.as_view(), name='schema'), 
    path('swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('JKR.home.urls')),
    path('docs/', include(('JKR.documentation.api.urls', 'documentation'), namespace='docs')),
    path('snippets/', include('JKR.snippets.api.urls')),
]

JKR/documentation/models.py
from django.db import models
from ckeditor.fields import RichTextField

class Documentation(models.Model):
    title = models.CharField(max_length=100)
    body = RichTextField(null=True, blank=True)
    is_active = models.BooleanField()
    
    created_at = models.DateTimeField(blank=True)
    modified_by = models.DateTimeField(blank=True)

JKR/home/models.py
from django.db import models

# Create your models here.

JKR/snippets/models.py
from django.db import models
from pygments.lexers import get_all_lexers
from pygments.styles import get_all_styles

LEXERS = [item for item in get_all_lexers() if item[1]]
LANGUAGE_CHOICES = sorted([(item[1][0], item[0]) for item in LEXERS])
STYLE_CHOICES = sorted([(item, item) for item in get_all_styles()])

class Snippets(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    code = models.TextField()
    linenos = models.BooleanField(default=False)
    language = models.CharField(choices=LANGUAGE_CHOICES, default='python', max_length=100)
    style = models.CharField(choices=STYLE_CHOICES, default='friendly', max_length=100)

    created_at = models.DateTimeField()
    modified_by = models.DateTimeField()


    class Meta:
        ordering = ['created_at']

JKR/documentation/forms.py
from django import forms
from JKR.documentation.models import Documentation

class DocumentationForm(forms.ModelForm):
    class Meta:
        model = Documentation
        fields = '__all__'

JKR/documentation/api/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from rest_framework.views import APIView
from JKR.documentation.models import Documentation
from JKR.documentation.api.serializers import DocumentationSerialzier
from JKR.documentation.forms import DocumentationForm

class ListItems(APIView):

    def get(self, request):
        documentation = Documentation.objects.all()
        form = DocumentationForm()
        context = {
            'documentation': documentation,
            'form' : form

        }
        return render(request, 'documentations/create.html', context)
    
    def post(self, request):
        form = DocumentationForm()
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(request.path)
        documentation = Documentation.objects.all()
        context = {
            'documentation': documentation, 
            'form': form
        }
        return render(request, 'documentations/create.html', context)

JKR/documentation/views.py
from django.shortcuts import render

# Create your views here.

JKR/home/views.py
from rest_framework import viewsets
from django.views.generic import TemplateView


class HomePage(TemplateView):
    template_name = "homes/index.html" 
class DocumentationPage(TemplateView):
    template_name = "homes/documentation.html"

# class Home(viewsets.Viewset):

JKR/snippets/api/views.py
from rest_framework.response import Response
from rest_framework import status
from rest_framework.views import APIView
from JKR.snippets.models import Snippets
from JKR.snippets.api.serializers import SnippetsSerializer


class ListItems(APIView):

    def get(self, request):
        snippets = Snippets.objects.all()
        serializer = SnippetsSerializer(snippets, many=True)
        return Response(serializer.data)
    
    def post(self, request):
        serializer = SnippetsSerializer(data=request.data)
        if(serializer.is_valid()):
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

JKR/snippets/views.py
from django.shortcuts import render

# Create your views here.

JKR/documentation/templates/documentations/create.html
{% extends "homes/home.html" %}
{% block content %}

<br><br><br><br><br><br><br><br>
<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title mb-0">Add the contents</h4>
            </div>
            {{form.errors}}
            <div class="card-body">
                <form method='POST'>
                    {% csrf_token %}
                    {{form.media}}

                    <div class="form-group">
                        <label>Title</label>
                        {{form.title}}
                    </div>
                    <div class="form-group">
                        <label>Add Body</label>
                        {{form.body}}
                    </div>



                    <div class="text-right">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

JKR/home/templates/homes/documentation.html
{% extends "homes/home.html" %}


{% block content %}

    <p>Welcome to the homepage of my awesome site.</p>
    <br><br><br><br><br><br><br>
    <a href="{% url 'docs:create_documentation' %}" class="btn btn-primary">Add contents</a>

{% endblock %}